Project-Unifest/unifest-web

.github/workflows/deploy-github-pages.yml
.github/workflows/vercel-pull-request.yml
src/features/booth/ui/Button.tsx
src/features/booth/ui/DeleteButton.tsx
src/features/booth/ui/EditButton.tsx
src/features/booth/ui/EditMenuBox.tsx
src/widgets/add-booth/ui/Map.tsx
src/widgets/add-booth/ui/SelectMode.tsx
src/widgets/add-booth/ui/SetCategory.tsx
src/widgets/add-booth/ui/SetDescription.tsx
src/widgets/add-booth/ui/SetName.tsx
src/widgets/booth/ui/Edit.tsx
src/widgets/boothList/ui/BoothList.tsx
src/widgets/header/ui/Header.tsx
src/widgets/sign-in/ui/SignIn.tsx
src/widgets/sign-up/ui/SignUp.tsx
yarn.lock

CD: rename branches for github actions

---

.github/workflows/deploy-github-pages.yml
.github/workflows/vercel-merge.yml

`vercel-pull-request.yml` create a preview on pull request.
`vercel-merge.yml` deploy to vercel production on merge.

Deploy to vercel on merge

---

.github/workflows/deploy-github-pages.yml

https://github.com/actions/deploy-pages/issues/271

CI: set environment to github-pages

---

src/widgets/sign-up/lib/sign-up-schema.ts

feat: change prop name

---

src/widgets/sign-up/ui/SignUp.tsx

hotfix: change option name

---

src/widgets/sign-up/lib/sign-up-schema.ts
src/widgets/sign-up/ui/SignUp.tsx

hotfix: invalid schema prop

---

next.config.mjs

hotfix: change config hostname for production env

---

src/widgets/add-booth/ui/Map.tsx
src/widgets/booth/ui/AddMap.tsx
src/widgets/booth/ui/EditMap.tsx

fix: enable zooming and panning

---

.github/workflows/deploy-github-pages.yml
.github/workflows/playwright.yml

CI: run add missing env vars

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.lintstagedrc.js

노트북이 없어서 github codespaces를 통해 어디서나 웹에서 개발 환경을 실행할 수 있도록 설정하였습니다.
- container에 vscode extension을 넣어서 실행될 때마다 항상 vscode extension이 설치되도록 설정
- 현재 작업 진행에 필요한 environment variable을 container에 추가. secrets 같은 경우 repository setting > development environment에서 넣을 수 있다고 합니다.

Github codespaces support

---

.devcontainer/devcontainer.json

Since it doesn't install the dependencies and playwright by default, I added the commands explicitly in devcontainer.json.

build: add post create command

---

mocks/api/handlers.ts
mocks/api/hello.ts
mocks/api/members.ts
src/app/model/useMSW.ts
src/app/ui/MSWProvider.tsx
src/entities/booth/ui/Item.tsx
src/widgets/add-booth/ui/SetDescription.tsx

- booth 이름은 한 줄이 넘어갈 경우 ellipsis(...)으로 표시합니다.
- booth 설명은 세 줄이 넘어갈 경우 ellipsis(...)으로 표시합니다.
- api server 오류로 인하여 부스를 생성하는 e2e 테스트를 로컬에서 수행하지 않고 merge할 계획입니다.
- api server 오류로 인해 e2e 테스트는 github actions로 실행할 경우 실패합니다.

Summarize with ellipsis when booth name or description overflows

---

package.json

#29 에서 제시된 문제를 해결할 수 있는 script를 package.json에 추가하였습니다.

Forward port for playwright ui mode

---

src/widgets/queue/ui/index.tsx

members/my 호출하는 boothList.tsx 보고 해결했어요

fix : waiting list failure when refresh

---

app/layout.tsx
package.json
yarn.lock

infra: setup google analytics

---

app/layout.tsx

To manage google analytics of all platforms in one account, I changed the google analytics

infra: change google analytics id(account)

---

app/layout.tsx

I set up google tag manager since google analytics can't track down user info

infra: set up google tag manger

---

documents/pull-requests/cloudflare-image-loader.md
imageLoader.ts
next.config.mjs

Cloudflare의 이미지 최적화 기능을 활용하기 위해 Next.js의 이미지 로더를 Cloudflare의 커스텀 이미지 로더로 변경했습니다.
세부 내용:
1. `imageLoader.ts` 파일 추가
- Cloudflare의 이미지 최적화 API를 사용하는 커스텀 이미지 로더 구현
- 개발 환경에서는 기본 이미지 URL 사용
- 프로덕션 환경에서는 Cloudflare CDN을 통한 이미지 최적화 적용
2. `next.config.mjs` 수정
- 기존 remotePatterns 설정 제거
- 커스텀 이미지 로더 설정 추가
1. 개발 환경(`NODE_ENV === "development"`)
- 기존 이미지 URL을 그대로 사용
- 이미지 최적화 없이 직접 서빙
2. 프로덕션 환경
- Cloudflare의 이미지 최적화 API 사용
- `/cdn-cgi/image/` 경로를 통해 이미지 최적화 적용
- width와 quality 파라미터를 통한 이미지 최적화 지원

infra: use cloudflare's custom image loader

---

imageLoader.ts

Next.js의 Image 컴포넌트에서 외부 이미지를 사용할 수 있도록 imageLoader에 예외처리를 추가하였습니다.
세부 내용:
1. `imageLoader.ts` 수정
- 외부 이미지 도메인을 위한 예외처리 추가

외부 이미지를 사용할 수 있도록 imageLoader에 예외 처리 추가

---

src/features/auth/model/auth.ts

- 가천대의 schoolId가 16인줄 알았는데 이거 festivalId였음을 확인했습니다
- 올바른 ID인 6으로 정정했습니다.

hotfix : prod 환경에서의 schoolId 수정

---

src/shared/lib/product/types.ts
src/shared/lib/promise.ts
src/widgets/booth/model/booth-edit.ts
src/widgets/booth/ui/Edit.tsx

AS-IS
- for문을 사용하여 비동기 작업을 순차적으로 실행했습니다.
- 문제점: for문 같은 경우에는 어떤 작업이 이루어지는지 명시적으로 코드가 작성되어 한눈에 보기 어렵습니다.
TO-BE
- reduce를 사용하여 비동기 작업을 순차적으로 실행하는 로직을 작성했습니다.
- reduced를 사용한 내부 구현이 너무 복잡해지기에 각 요소에서 실행되어야 하는 비동기 함수 및 배열을 받아 처리하는 helper function으로 모듈화했습니다.
- 장점: 각 배열마다 어떤 비동기 태스크가 실행되는지 파악하기 쉬워졌습니다.(선언적)

refactor: 여러개의 async task를 순차적으로 실행하기 위한 sequence helper function 추가

---

src/widgets/booth/ui/Edit.tsx

#93 여기서 잘못들어간 코드 핫픽스해서 다시 올립니다.

hotfix : 다시 500자 제한
